seed_everything: 1234
ckpt_path: null

trainer:
  fast_dev_run: false
  accelerator: gpu
  devices: [0]
  num_nodes: 1
  precision: bf16-mixed
  max_epochs: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 100
  limit_test_batches: 1

  callbacks: []
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      # save_dir: "/scratch/mtg/akanatas/output/extracted_embeddings/musicfm_mtg-jamendo/"
      save_dir: "/gpfs/projects/mtg/projects/layerbylayer/output/extracted_embeddings/musicfm_mtg-jamendo/"
      # save_dir: "/home/akanatas/output/extracted_embeddings/musicfm_mtg-jamendo/"

model:
  class_path: marble.tasks.ExtractRepresentations.extract.ExtractRepresentationsTask
  init_args:
    sample_rate: 24000
    use_ema: false

    encoder:
      class_path: marble.encoders.MusicFM.model.MusicFM_Encoder
      init_args:
        pre_trained_folder: null
        train_mode: freeze
      
    emb_transforms:
      - class_path: marble.modules.transforms.LayerSelector
        init_args:
          layers: ["all"]
      - class_path: marble.modules.transforms.TimeAvgPool
    
    extraction:
      split: test
      # output_dir: /scratch/mtg/akanatas/output/extracted_embeddings/musicfm_mtg-jamendo/
      output_dir: /gpfs/projects/mtg/projects/layerbylayer/output/extracted_embeddings/musicfm_mtg-jamendo/
      # output_dir: /home/akanatas/output/extracted_embeddings/musicfm_mtg-jamendo/
      max_samples: 10000
      sampling_seed: 17
      save_frame_level: false
      save_sequence_level: true
      
      augmentation:
        num_augmentations: 2
        seed: 42
        transforms:
          - PolarityInversion:
              p: 0.5
          - Gain:
              min_gain_db: -6.0
              max_gain_db: 0.0
              p: 0.5
          - AddGaussianNoise:
              min_amplitude: 0.001
              max_amplitude: 0.01
              p: 0.6
          - BandPassFilter:
              min_center_freq: 200.0
              max_center_freq: 4000.0
              min_bandwidth_fraction: 0.6
              max_bandwidth_fraction: 1.0
              p: 0.25
          - Shift:
              min_shift: -0.1
              max_shift: 0.1
              rollover: true
              p: 0.4
          - LowPassFilter:
              min_cutoff_freq: 3000.0
              max_cutoff_freq: 8000.0
              p: 0.1

data:
  class_path: marble.tasks.RawAudio.datamodule.RawAudioDataModule
  init_args:
    batch_size: 32
    num_workers: 16

    train:
      class_path: marble.tasks.RawAudio.datamodule.SimpleRawAudioDataset
      init_args:
        audio_dir: /gpfs/projects/mtg/audio/stable/mtg-jamendo/raw_30s/audio
        sample_rate: 24000
        channels: 1
        clip_seconds: 15.0
        min_clip_ratio: 0.8
        channel_mode: mix
        extensions: ['.wav', '.flac', '.mp3', '.webm', '.mp4']
        recursive: true
        max_files: null
        random_seed: 42
        backend: "soundfile"
    val:
      class_path: marble.tasks.RawAudio.datamodule.SimpleRawAudioDataset
      init_args:
        audio_dir: /gpfs/projects/mtg/audio/stable/mtg-jamendo/raw_30s/audio
        sample_rate: 24000
        channels: 1
        clip_seconds: 15.0
        min_clip_ratio: 0.8
        channel_mode: mix
        extensions: ['.wav', '.flac', '.mp3', '.webm', '.mp4']
        recursive: true
        max_files: null
        random_seed: 42
        backend: "soundfile"
    test:
      class_path: marble.tasks.RawAudio.datamodule.SimpleRawAudioDataset
      init_args:
        audio_dir: /gpfs/projects/mtg/audio/stable/mtg-jamendo/raw_30s/audio
        # audio_dir: /mnt/mtg/audio/stable/mtg-jamendo/raw_30s/audio
        sample_rate: 24000
        channels: 1
        clip_seconds: 15.0
        min_clip_ratio: 0.8
        channel_mode: mix
        extensions: ['.wav', '.flac', '.mp3', '.webm', '.mp4']
        recursive: true
        max_files: 1000
        random_seed: 42
        backend: "soundfile"

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-3

lr_scheduler: null
